name: Deploy F&P Legaltec to Webempresa

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy by FTPS
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Upload website by FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ns50141.webempresa.eu
          username: miguelfloren@pflegaltec.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.claude/**
            **/README.md
            **/.cpanel.yml
